services:
  arelle:
    build:
      context: ./arelle-web-service
    image: arelle
    container_name: arelle
    ports:
      - "8081:8080"
    expose:
      - "8081"
    volumes:
      - ./volumes/financial-reports:/var/lib/financial-reports
      - ./volumes/taxonomies:/var/lib/taxonomies

  financialreportservice:
    build:
      context: ./financialreportservice
    image: financialreportservice
    container_name: financialreportservice
    ports:
      - "8082:8080"
    expose:
      - "8082"
    environment:
      ARELLE_URL: arelle
      ARELLE_PORT: 8080
      XBRLFILINGS_URL: "https://filings.xbrl.org/"
#volumes:
#  financial-reports-volume:
#    name: financial-reports