services:
  arelle:
    build:
      context: ./arelle-web-service
    image: arelle
    container_name: arelle
    ports:
      - "8081:8080"
    expose:
      - "8081"
    volumes:
      - ./volumes/taxonomies:/var/lib/taxonomies

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log:/var/log/rabbitmq

  schedulingservice:
    build:
      context: ./schedulingservice
    image: schedulingservice
    container_name: schedulingservice
    ports:
      - "8082:8080"
    expose:
      - "8082"
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

  financialreportservice:
    build:
      context: ./financialreportservice
    image: financialreportservice
    container_name: financialreportservice
    ports:
      - "8083:8080"
    expose:
      - "8083"
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"
      ARELLE_URL: arelle
      ARELLE_PORT: 8080
      XBRLFILINGS_URL: "https://filings.xbrl.org/"

  stockdataservice:
    build:
      context: ./stockdataservice
    image: stockdataservice
    container_name: stockdataservice
    ports:
      - "8084:8080"
    expose:
      - "8084"
    depends_on:
      rabbitmq:
        condition: service_started
      influxdb:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"
      INFLUX_HOST: "http://influxdb:8086"
      INFLUX_ORG: "mystockdata"
      INFLUX_BUCKET: "stockdata"
      INFLUX_TOKEN: "uJ1kurH8Y02A7mEjPB5SME1fXRpCaqTsoYtad4k-m5MQl-Xl8IPJqJdrjBd4TUBLNG9SYiKrDitr6k6wDSIRTQ=="

  influxdb:
    image: influxdb:2.3.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb2
      - ./volumes/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "user"
      DOCKER_INFLUXDB_INIT_PASSWORD: "password"
      DOCKER_INFLUXDB_INIT_ORG: "mystockdata"
      DOCKER_INFLUXDB_INIT_BUCKET: "stockdata"
      DOCKER_INFLUXDB_INIT_TOKEN: "token"
      DOCKER_INFLUXDB_INIT_RETENTION: "0"