services:
  arelle:
    build:
      context: ./arelle-web-service
    image: arelle
    container_name: arelle
    ports:
      - "8081:8080"
    expose:
      - "8081"
    volumes:
      - ./volumes/taxonomies:/var/lib/taxonomies
      - ./volumes/financial_reports:/var/lib/financial-reports

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log:/var/log/rabbitmq

  schedulingservice:
    build:
      context: ./schedulingservice
    image: schedulingservice
    container_name: schedulingservice
    ports:
      - "8082:8080"
    expose:
      - "8082"
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"

  financialreportservice:
    build:
      context: ./financialreportservice
    image: financialreportservice
    container_name: financialreportservice
    ports:
      - "8083:8080"
    expose:
      - "8083"
    depends_on:
      rabbitmq:
        condition: service_started
      mongodb:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"
      ARELLE_URL: arelle
      ARELLE_PORT: "8080"
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: "8087"
      SPRING_DATA_MONGODB_USERNAME: "mongoUsername"
      SPRING_DATA_MONGODB_PASSWORD: "mongoPassword"
      SPRING_DATA_MONGODB_DATABASE: "financialreportdatabase"

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "8087:27017"
    expose:
      - "8087"
    volumes:
      - ./volumes/mongodb/data:/data/db
      - ./volumes/mongodb/config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoUsername"
      MONGO_INITDB_ROOT_PASSWORD: "mongoPassword"

  stockdataservice:
    build:
      context: ./stockdataservice
    image: stockdataservice
    container_name: stockdataservice
    ports:
      - "8084:8080"
    expose:
      - "8084"
    depends_on:
      rabbitmq:
        condition: service_started
      influxdb:
        condition: service_started
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"
      INFLUX2_HOST: "http://influxdb:8086"
      INFLUX2_ORG: "mystockdata"
      INFLUX2_BUCKET: "stockdata"
      INFLUX2_TOKEN: "adminToken"

  influxdb:
    image: influxdb:2.3.0
    container_name: influxdb
    ports:
      - "8086:8086"
    expose:
      - "8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb2
      - ./volumes/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "user"
      DOCKER_INFLUXDB_INIT_PASSWORD: "password"
      DOCKER_INFLUXDB_INIT_ORG: "mystockdata"
      DOCKER_INFLUXDB_INIT_BUCKET: "stockdata"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "adminToken"
      DOCKER_INFLUXDB_INIT_RETENTION: "0"