GET http://localhost:8085/v1/company/529900NNUPAGGOMPXZ31
Content-Type: application/json

###
GET http://localhost:8080/v1/company/retrieveDataForCompanies?aggregatedPriceInfoStart=2012-08-01T09:15:29.442856700Z&aggregatedPriceInfoEnd=2022-08-05T09:15:29.442856700Z&lei=529900NNUPAGGOMPXZ31&lei=529900D6BF99LW9R2E68&lei=549300JSX0Z4CW0V5023
Content-Type: application/json

###
PUT http://localhost:8085/v1/company?addToWatchList=true
Content-Type: application/json

[
  {
    "lei": "529900NNUPAGGOMPXZ31",
    "securities": [
      {
        "isin": "DE0007664039",
        "symbols": [
          {
            "symbol": "VOW3.DE",
            "exchange": "XETRA"
          }
        ]
      }
    ]
  },
  {
    "lei": "529900D6BF99LW9R2E68",
    "securities": [
      {
        "isin": "DE0007164600",
        "symbols": [
          {
            "symbol": "SAP.DE",
            "exchange": "XETRA"
          }
        ]
      }
    ]
  },
  {
    "lei": "549300JSX0Z4CW0V5023",
    "securities": [
      {
        "isin": "DE000A1EWWW0",
        "symbols": [
          {
            "symbol": "ADS.DE",
            "exchange": "XETRA"
          }
        ]
      }
    ]
  }
]