### CSV
GET http://localhost:8080/v1/composedData/aggregatedPriceInformation/csv?lei=529900NNUPAGGOMPXZ31&lei=529900D6BF99LW9R2E68&lei=549300JSX0Z4CW0V5023&missingValueStrategy=LAST_VALUE&indicatorNames=SMA&indicatorNames=PER&ifrsFact=ifrs-full:DilutedEarningsLossPerShare&ifrsFact=ifrs-full:Equity&start=2018-08-01T09:15:29.442856700Z&end=2022-08-01T09:15:29.442856700Z
Accept: text/csv

### CSV
GET http://localhost:8080/v1/composedData/precisePriceInformation/csv?symbols=SAP.DE&symbols=TSLA&symbols=AMC&missingValueStrategy=LAST_VALUE&indicatorNames=SMA
Accept: text/csv
