spring:
  application:
    name: financialreportservice
  cloud:
    function:
      definition: financialReportEventConsumer
    stream:
      bindings:
        financialReportEventConsumer-in-0:
          destination: financialReportEvent
  mongodb:
    embedded:
      version: 4.4.9
arelle:
  url: arelle
  port: 8081