spring:
  application:
    name: financialreportservice
  profiles:
    active: default
  cloud:
      function:
        definition: financialReportEventConsumer
      stream:
        bindings:
          financialReportEventConsumer-in-0:
            destination: financialReportEvent
arelle:
  url: localhost
  port: 8081
logging.level.com.mystockdata: DEBUG