financialreportservice:
  host: "financialreportservice"
  port: "8083"
stockdataservice:
  host: "stockdataservice"
  port: "8084"
composerservice:
  host: "composerservice"
  port: "8085"
logging.level.com.mystockdata: DEBUG
logging.level.org.springframework.cloud.gateway: DEBUG