spring:
  application:
    name: composerservice
  mongodb:
    embedded:
      version: 4.4.9
financialreportservice:
  host: "financialreportservice"
  port: "8083"
stockdataservice:
  host: "stockdataservice"
  port: "8084"