# @name Companies_get
GET http://localhost:8080/v1/stockdata/company?lei=529900NNUPAGGOMPXZ31&lei=529900D6BF99LW9R2E68
Content-Type: application/json

###
# @name Companies_add
PUT http://localhost:8080/v1/stockdata/company?addToWatchList=true
Content-Type: application/json

[
  {
    "lei": "529900NNUPAGGOMPXZ31",
    "securities": [
      {
        "isin": "DE0007664039",
        "symbols": [
          {
            "symbol": "VOW3.DE",
            "system": "Yahoo Finance",
            "exchange": "XETRA"
          }
        ]
      }
    ]
  },
  {
    "lei": "529900D6BF99LW9R2E68",
    "securities": [
      {
        "isin": "DE0007164600",
        "symbols": [
          {
            "symbol": "SAP.DE",
            "system": "Yahoo Finance",
            "exchange": "XETRA"
          }
        ]
      }
    ]
  },
  {
    "lei": "549300JSX0Z4CW0V5023",
    "securities": [
      {
        "isin": "DE000A1EWWW0",
        "symbols": [
          {
            "symbol": "ADS.DE",
            "system": "Yahoo Finance",
            "exchange": "XETRA"
          }
        ]
      }
    ]
  }
]