GET http://localhost:8084/v1/watchlist
Content-Type: application/json

###
PUT http://localhost:8084/v1/watchlist?symbol=VOW3.DE&symbol=SAP.DE&symbol=ADS.DE&symbol=TSLA&symbol=AMC
Content-Type: application/json

###
DELETE http://localhost:8084/v1/watchlist?symbol=VOW3.DE
Content-Type: application/json