
GET http://localhost:8084/v1/watchlist
Content-Type: application/json

###
PUT http://localhost:8084/v1/watchlist?lei=529900D6BF99LW9R2E68&lei=529900NNUPAGGOMPXZ31
Content-Type: application/json

###
DELETE http://localhost:8084/v1/watchlist?symbol=VOW3.DE
Content-Type: application/json