GET http://localhost:8084/v1/watchlist
Content-Type: application/json

###
PUT http://localhost:8084/v1/watchlist?lei=test
Content-Type: application/json

###
DELETE http://localhost:8084/v1/watchlist?lei=test
Content-Type: application/json