spring:
  application:
    name: stockdataservice
  profiles:
    active: default
  cloud:
    function:
      definition: stockDataEventConsumer
    stream:
      bindings:
        stockDataEventConsumer-in-0:
          destination: stockDataEvent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
influx:
  host: http://localhost:8086
  org: mystockdata
  bucket: stockdata
  token: uJ1kurH8Y02A7mEjPB5SME1fXRpCaqTsoYtad4k-m5MQl-Xl8IPJqJdrjBd4TUBLNG9SYiKrDitr6k6wDSIRTQ==
logging.level.com.mystockdata: DEBUG