spring:
  application:
    name: stockdataservice
  cloud:
    function:
      definition: stockDataEventConsumer
    stream:
      bindings:
        stockDataEventConsumer-in-0:
          destination: stockDataEvent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: "localhost"
      port: 27017
      username: "stockdataservice"
      password: "mongoPassword"
      database: "stockdataservice"
      authentication-database: admin
influx2:
  host: http://localhost:8086
  org: mystockdata
  bucket: stockdata
  token: adminToken
logging.level.com.mystockdata: DEBUG
logging.level.org.springframework.data.mongodb.repository.query: DEBUG