spring:
  data:
    mongodb:
      host: "mongodb"
      port: 27017
      username: "mongoUsername"
      password: "mongoPassword"
      database: "financialreportdatabase"
      authentication-database: admin