package com.mystockdata.financialreportservice.financialreports

import com.mystockdata.financialreportservice.arelle.Item
import java.math.BigDecimal

data class IFRSStatementOfFinancialPositionOrderOfLiquidity (
    var ifrs_full_PropertyPlantAndEquipment: BigDecimal? = null,
    var ifrs_full_InvestmentProperty: BigDecimal? = null,
    var ifrs_full_Goodwill: BigDecimal? = null,
    var ifrs_full_IntangibleAssetsOtherThanGoodwill: BigDecimal? = null,
    var ifrs_full_OtherFinancialAssets: BigDecimal? = null,
    var ifrs_full_OtherNonfinancialAssets: BigDecimal? = null,
    var ifrs_full_InvestmentAccountedForUsingEquityMethod: BigDecimal? = null,
    var ifrs_full_InvestmentsInSubsidiariesJointVenturesAndAssociates: BigDecimal? = null,
    var ifrs_full_BiologicalAssets: BigDecimal? = null,
    var ifrs_full_NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleOrAsHeldForDistributionToOwners: BigDecimal? = null,
    var ifrs_full_InventoriesTotal: BigDecimal? = null,
    var ifrs_full_CurrentTaxAssets: BigDecimal? = null,
    var ifrs_full_DeferredTaxAssets: BigDecimal? = null,
    var ifrs_full_TradeAndOtherReceivables: BigDecimal? = null,
    var ifrs_full_CashAndCashEquivalents: BigDecimal? = null,
    var ifrs_full_NoncashAssetsPledgedAsCollateralForWhichTransfereeHasRightByContractOrCustomToSellOrRepledgeCollateral: BigDecimal? = null,
    var ifrs_full_Assets: BigDecimal? = null,
    var ifrs_full_IssuedCapital: BigDecimal? = null,
    var ifrs_full_RetainedEarnings: BigDecimal? = null,
    var ifrs_full_SharePremium: BigDecimal? = null,
    var ifrs_full_TreasuryShares: BigDecimal? = null,
    var ifrs_full_OtherEquityInterest: BigDecimal? = null,
    var ifrs_full_OtherReserves: BigDecimal? = null,
    var ifrs_full_EquityAttributableToOwnersOfParent: BigDecimal? = null,
    var ifrs_full_NoncontrollingInterests: BigDecimal? = null,
    var ifrs_full_Equity: BigDecimal? = null,
    var ifrs_full_TradeAndOtherPayables: BigDecimal? = null,
    var ifrs_full_ProvisionsForEmployeeBenefits: BigDecimal? = null,
    var ifrs_full_OtherProvisions: BigDecimal? = null,
    var ifrs_full_Provisions: BigDecimal? = null,
    var ifrs_full_OtherFinancialLiabilities: BigDecimal? = null,
    var ifrs_full_OtherNonfinancialLiabilities: BigDecimal? = null,
    var ifrs_full_CurrentTaxLiabilities: BigDecimal? = null,
    var ifrs_full_DeferredTaxLiabilities: BigDecimal? = null,
    var ifrs_full_LiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale: BigDecimal? = null,
    var ifrs_full_Liabilities: BigDecimal? = null,
    var ifrs_full_EquityAndLiabilities: BigDecimal? = null
){
    fun setValue(item: Item) = keyLambdaMap[item.name]?.invoke(this, item)
}
private val keyLambdaMap = mapOf<String, (IFRSStatementOfFinancialPositionOrderOfLiquidity, Item) -> Unit>(
    "ifrs-full:PropertyPlantAndEquipment" to {statement, item -> statement.ifrs_full_PropertyPlantAndEquipment = item.valueNumeric},
    "ifrs-full:InvestmentProperty" to {statement, item -> statement.ifrs_full_InvestmentProperty = item.valueNumeric},
    "ifrs-full:Goodwill" to {statement, item -> statement.ifrs_full_Goodwill = item.valueNumeric},
    "ifrs-full:IntangibleAssetsOtherThanGoodwill" to {statement, item -> statement.ifrs_full_IntangibleAssetsOtherThanGoodwill = item.valueNumeric},
    "ifrs-full:OtherFinancialAssets" to {statement, item -> statement.ifrs_full_OtherFinancialAssets = item.valueNumeric},
    "ifrs-full:OtherNonfinancialAssets" to {statement, item -> statement.ifrs_full_OtherNonfinancialAssets = item.valueNumeric},
    "ifrs-full:InvestmentAccountedForUsingEquityMethod" to {statement, item -> statement.ifrs_full_InvestmentAccountedForUsingEquityMethod = item.valueNumeric},
    "ifrs-full:InvestmentsInSubsidiariesJointVenturesAndAssociates" to {statement, item -> statement.ifrs_full_InvestmentsInSubsidiariesJointVenturesAndAssociates = item.valueNumeric},
    "ifrs-full:BiologicalAssets" to {statement, item -> statement.ifrs_full_BiologicalAssets = item.valueNumeric},
    "ifrs-full:NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleOrAsHeldForDistributionToOwners" to {statement, item -> statement.ifrs_full_NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSaleOrAsHeldForDistributionToOwners = item.valueNumeric},
    "ifrs-full:InventoriesTotal" to {statement, item -> statement.ifrs_full_InventoriesTotal = item.valueNumeric},
    "ifrs-full:CurrentTaxAssets" to {statement, item -> statement.ifrs_full_CurrentTaxAssets = item.valueNumeric},
    "ifrs-full:DeferredTaxAssets" to {statement, item -> statement.ifrs_full_DeferredTaxAssets = item.valueNumeric},
    "ifrs-full:TradeAndOtherReceivables" to {statement, item -> statement.ifrs_full_TradeAndOtherReceivables = item.valueNumeric},
    "ifrs-full:CashAndCashEquivalents" to {statement, item -> statement.ifrs_full_CashAndCashEquivalents = item.valueNumeric},
    "ifrs-full:NoncashAssetsPledgedAsCollateralForWhichTransfereeHasRightByContractOrCustomToSellOrRepledgeCollateral" to {statement, item -> statement.ifrs_full_NoncashAssetsPledgedAsCollateralForWhichTransfereeHasRightByContractOrCustomToSellOrRepledgeCollateral = item.valueNumeric},
    "ifrs-full:Assets" to {statement, item -> statement.ifrs_full_Assets = item.valueNumeric},
    "ifrs-full:IssuedCapital" to {statement, item -> statement.ifrs_full_IssuedCapital = item.valueNumeric},
    "ifrs-full:RetainedEarnings" to {statement, item -> statement.ifrs_full_RetainedEarnings = item.valueNumeric},
    "ifrs-full:SharePremium" to {statement, item -> statement.ifrs_full_SharePremium = item.valueNumeric},
    "ifrs-full:TreasuryShares" to {statement, item -> statement.ifrs_full_TreasuryShares = item.valueNumeric},
    "ifrs-full:OtherEquityInterest" to {statement, item -> statement.ifrs_full_OtherEquityInterest = item.valueNumeric},
    "ifrs-full:OtherReserves" to {statement, item -> statement.ifrs_full_OtherReserves = item.valueNumeric},
    "ifrs-full:EquityAttributableToOwnersOfParent" to {statement, item -> statement.ifrs_full_EquityAttributableToOwnersOfParent = item.valueNumeric},
    "ifrs-full:NoncontrollingInterests" to {statement, item -> statement.ifrs_full_NoncontrollingInterests = item.valueNumeric},
    "ifrs-full:Equity" to {statement, item -> statement.ifrs_full_Equity = item.valueNumeric},
    "ifrs-full:TradeAndOtherPayables" to {statement, item -> statement.ifrs_full_TradeAndOtherPayables = item.valueNumeric},
    "ifrs-full:ProvisionsForEmployeeBenefits" to {statement, item -> statement.ifrs_full_ProvisionsForEmployeeBenefits = item.valueNumeric},
    "ifrs-full:OtherProvisions" to {statement, item -> statement.ifrs_full_OtherProvisions = item.valueNumeric},
    "ifrs-full:Provisions" to {statement, item -> statement.ifrs_full_Provisions = item.valueNumeric},
    "ifrs-full:OtherFinancialLiabilities" to {statement, item -> statement.ifrs_full_OtherFinancialLiabilities = item.valueNumeric},
    "ifrs-full:OtherNonfinancialLiabilities" to {statement, item -> statement.ifrs_full_OtherNonfinancialLiabilities = item.valueNumeric},
    "ifrs-full:CurrentTaxLiabilities" to {statement, item -> statement.ifrs_full_CurrentTaxLiabilities = item.valueNumeric},
    "ifrs-full:DeferredTaxLiabilities" to {statement, item -> statement.ifrs_full_DeferredTaxLiabilities = item.valueNumeric},
    "ifrs-full:LiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale" to {statement, item -> statement.ifrs_full_LiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale = item.valueNumeric},
    "ifrs-full:Liabilities" to {statement, item -> statement.ifrs_full_Liabilities = item.valueNumeric},
    "ifrs-full:EquityAndLiabilities" to {statement, item -> statement.ifrs_full_EquityAndLiabilities = item.valueNumeric}
)